version: "2.1"
services:
  code-server:
    build:
      context: .
    container_name: code-server
    ports:
      - 8989:8989
    volumes:
      - "${PWD}:/home/coder/project"
    restart: unless-stopped
    env_file:
      - .env
