version: "2.1"
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile.pi
    container_name: code-server
    ports:
      - 8989:8989
    volumes:
      - "${PROJECT_DIR}:/home/coder/project"
    restart: unless-stopped
    env_file:
      - .env
