version: "2.1"
services:
  code-server:
    build:
      context: ./services/vscode
      dockerfile: Dockerfile
    container_name: code-server
    ports:
      - 8989:8989
    volumes:
      - "${PWD}:/home/coder/project"
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 1337:80
    depends_on:
      - "code-server"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    # restart: unless-stopped